[Interface]
Address = 10.66.66.4/32
DNS = 1.1.1.1
PrivateKey = <ANDROID_PRIVATE_KEY>

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = <SERVER_PUBLIC_IP>:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

