[Interface]
Address = 10.66.66.2/32
MTU = 1340
DNS = 1.1.1.1
PrivateKey = <IPHONE_PRIVATE_KEY>

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = 43.160.239.253:443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
