[Interface]
Address = 10.66.66.3/32
MTU = 1340
DNS = 1.1.1.1
PrivateKey = <WINDOWS_PRIVATE_KEY>
# Official WireGuard Windows kill-switch: OFF

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = 43.160.239.253:443
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
